manifest = "881f2dcc1a1d8d3f4dbcdfb5b485c7a12ff14691b0fc16531e92a98c0a8b8114"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type-traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "f9d6a7b63ef2902777b6078fdebc54e7a57aac03"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "4392ed19b232ed2dde7623843d7e30ef669d860e"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "84411b155dae6f08ea749bdeb1e71aecd0718d52"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "e8b834a93f7ba935aa63a3d6690804f3bd2b0963"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "branch=master" ]
revision = "a1873af9c1d31fb8ec2a87482b6bb9729439b4ac"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "4d01d0f9c0ae3ae3cd20e3cbfddbc9909ce8e064"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "4d0a507c0d1a1011c5a98d57acc9f6b755141e4f"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "branch=master" ]
revision = "f04cf922658a7e03776631a96c3ad346ad179d5f"
