manifest = "34f07296f52e878fce932e55704c488ed8a5d142250666938d2d9737867f2f9b"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.43.0" ]
revision = "b372c24ab8b55df3a336bc4f0b200014369d6d96"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.43.0" ]
revision = "77ca029d6666ae6c9d11b7fae0f2c6424020fead"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.43.0" ]
revision = "250eb73a82e4412317ef1e1d3705ad97fd1cef6c"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.43.0" ]
revision = "71e2798b88ab175cc2c904a8d1863b69a02f9a09"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.43.0" ]
revision = "ef5e2df9e921bb8120a0d80847731139e0e37d7d"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.43.0" ]
revision = "d19e409d08aa20728074f8eda6d26546b3046789"
